name: Test Cases
on:
  push:
    branches:
      - master
      - issue-237-git-action
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test Cases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12.x']
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2

      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Use Node.js ${{ matrix['node-version'] }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix['node-version'] }}

      - name: Install Dependencies
        run: yarn install

      - name: Test Cases Using Firefox
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn test:firefox

      - name: Test Cases Using Chrome
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn test:chrome

      - name: Check Lint
        run: yarn lint

      - name: Build
        run: yarn build
